version: "3"
services:
  #  postgresql:
  #    image: postgres:12.0
  #    container_name: postgresql
  #    environment:
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=postgres
  #      - POSTGRES_DB=postgres
  #    ports:
  #      - "5432:5432"
  painter:
    container_name: painter
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            gunicorn settings.wsgi:application --bind 0.0.0.0:7979 --log-level debug --workers=2 --worker-class=gevent --worker-connections=100"
    ports:
      - "7979:7979"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.painter.rule=Host(`painter.kulpinov.site`)"
      - "traefik.http.services.painter.loadbalancer.server.port=7979"

volumes:
  media_volume:
  static_volume:
networks:
  web:
    external: true