# Generated by Django 4.1.7 on 2023-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Форма',
            },
        ),
    ]
