# Generated by Django 4.1.7 on 2023-04-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='number',
            field=models.TextField(),
        ),
    ]
